### ISSUE TITLE
Problem I encounter when I build FIES: undefined reference to `xmlStrcmp'

### ISSUE THREAD

**Issue by zujia** [ahoeller/fies#3]
I'm compiling the project FIES you posted on github. But I fall through a probelm when the build program come to this step "LINK  arm-softmmu/qemu-system-arm", it report some error like:

> fault-injection-library.o: In function `qmp_fault_reload':
> /home/yan/Documents/fies-master/fault-injection-library.c:621: undefined reference to `xmlCheckVersion'

There are many more below, but they are similar to the one above.
I use the ubuntu 14.04, and I can confirm that my libxml2 is installed properly. So I don't know what went wrong.
I would be very grateful if you can give me some help.

**Comment by shizi0123** [comment]
I have same errors，do  you solve this? if you do,please give me some help! Thanks!

**Comment by ahoeller** [comment]
Soulds like a linker problem. Does the command "xml2-config --libs" give a valid path? If so, you can try to manually give this path during the configuration step as --extra-ldflags argument. 
The readme has changed to put the LF variable into quotes. Have you tried this?

**Comment by shizi0123** [comment]
I have tried! but when I type :xml2-config --libs in terminal,the output is -lxml2 only. According to your idea,I should give lxml2 a valid path,is this right?

**Comment by shizi0123** [comment]
I searched command line：xml2-config --libs of libxml2 on line and found its output like this：-L/usr/lib/x86_64-linux-gnu -lxml2.So I thought libxml2's version maybe matters, I tried to install libxml2 of an older version，when I make，it have some errors. So, maybe there are some conflicts about Ubuntu version and libxml2 version,can you tell me your versions about the two?
Thanks!

**Comment by shizi0123** [comment]
I solved this problem,thanks for you two!

**Comment by Sayandeepsaha** [comment]
I am having the same problem with ubuntu 16.04. It seems that libxml2 cannot be linked. However I cannot figure out why because everything seems fine and I am using the latest installation manual for fies. Please help.

**Comment by Sayandeepsaha** [comment]
Error log:
LINK  arm-softmmu/qemu-system-arm
fault-injection-library.o: In function `qmp_fault_reload':
/home/sayandeep/fies/fault-injection-library.c:621: undefined reference to `xmlCheckVersion'
fault-injection-library.o: In function `parseFile':
/home/sayandeep/fies/fault-injection-library.c:541: undefined reference to `xmlParseFile'
/home/sayandeep/fies/fault-injection-library.c:548: undefined reference to `xmlDocGetRootElement'
/home/sayandeep/fies/fault-injection-library.c:557: undefined reference to `xmlStrcmp'
/home/sayandeep/fies/fault-injection-library.c:577: undefined reference to `xmlStrcmp'
...
...
...
....

**Comment by three791** [comment]
> 我解决了这个问题，谢谢你们两个！
